apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keruta-dev-ingress
  namespace: kigawa-net-keruta-dev
spec:
  ingressClassName: haproxy
  rules:
    - host: ktse-dev.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ktse-dev-svc
                port:
                  number: 8080
    - host: keruta-dev.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ktcl-front-dev-svc
                port:
                  number: 3000
    - host: ktcl-k8s-dev.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ktcl-k8s-dev-svc
                port:
                  number: 8081
